apiVersion: v1
kind: ConfigMap
metadata:
  name: mqmonitor-configmap
  namepsace: mq
type: Opaque
data:
  mqQueueManagerName: SMALLQM
  mqHostname: smallqm-ibm-mq.mq.svc.cluster.local
  mqPort: "1414"
  mqChannelName: SMALLQMCHL_NOTLS
  mqGenericQueueName: "*"
  monitorPeriod: "60"
  monitorThresholdRed: "0.9"
  monitorThresholdAmber: "0.5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqmonitor
  namepsace: mq
  labels:
    app: mqmonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqmonitor
  template:
    metadata:
      labels:
        app: mqmonitor
    spec:
      containers:
        - name: mqmonitor
          image: docker.io/koksing/mqmonitor:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: SPLUNK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mqmonitor-secret
                  key: splunkToken
            - name: SPLUNK_ENDPOINT
              valueFrom: 
                secretKeyRef:
                  name: mqmonitor-secret
                  key: splunkEndpoint
            - name: MQ_QUEUEMANAGERNAME
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqQueueManagerName
            - name: MQ_HOSTNAME
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqHostname
            - name: MQ_PORT
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqPort
            - name: MQ_CHANNELNAME
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqChannelName
            - name: MQ_GENERICQUEUENAME
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqGenericQueueName
            - name: MONITOR_PERIOD
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: monitorPeriod
            - name: MONITOR_THRESHOLDRED
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: monitorThresholdRed
            - name: MONITOR_THRESHOLDAMBER
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: monitorThresholdAmber