apiVersion: v1
kind: ConfigMap
metadata:
  name: mqmonitor-configmap
  namespace: mqmonitor
data:
  mqQueueManagerName: QM2
  mqHostname: qm2-ibm-mq.mq.svc.cluster.local
  mqPort: "1414"
  mqChannelName: QM2CHL_MTLS
  mqGenericQueueName: "*"
  monitorPeriod: "60"
  mqTlsMode: "mtls"
  mqTlsDebug: "false"
  mqTlsCipherSuite: "TLS_RSA_WITH_AES_256_GCM_SHA384"
  mqTlsKeystoreFilename: "/etc/certs/keystore.jks"
  mqTlsKeystoreType: "JKS"
  mqTlsTruststoreFilename: "/etc/certs/truststore.jks"
  mqTlsTruststoreType: "JKS"
  monitorThresholdRed: "0.9"
  monitorThresholdAmber: "0.5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqmonitor
  namespace: mqmonitor
  labels:
    app: mqmonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqmonitor
  template:
    metadata:
      labels:
        app: mqmonitor
    spec:
      imagePullSecrets:
        - name: quayio-pull-secret
      containers:
        - name: mqmonitor
          image: quay.io/kskhong/mqmonitor:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: SPLUNK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mqmonitor-secret
                  key: splunkToken
            - name: SPLUNK_ENDPOINT
              valueFrom: 
                secretKeyRef:
                  name: mqmonitor-secret
                  key: splunkEndpoint
            - name: MQ_QUEUEMANAGERNAME
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqQueueManagerName
            - name: MQ_HOSTNAME
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqHostname
            - name: MQ_PORT
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqPort
            - name: MQ_CHANNELNAME
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqChannelName
            - name: MQ_GENERICQUEUENAME
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqGenericQueueName
            - name: MONITOR_PERIOD
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: monitorPeriod
            - name: MONITOR_THRESHOLDRED
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: monitorThresholdRed
            - name: MONITOR_THRESHOLDAMBER
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: monitorThresholdAmber
            - name: MQ_TLS_MODE
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqTlsMode
            - name: MQ_TLS_CIPHER_SUITE
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqTlsCipherSuite
            - name: MQ_TLS_KEYSTORE_FILENAME
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqTlsKeystoreFilename
            - name: MQ_TLS_KEYSTORE_TYPE
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqTlsKeystoreType
            - name: MQ_TLS_TRUSTSTORE_FILENAME
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqTlsTruststoreFilename
            - name: MQ_TLS_TRUSTSTORE_TYPE
              valueFrom: 
                configMapKeyRef:
                  name: mqmonitor-configmap
                  key: mqTlsTruststoreType
            - name: MQ_TLS_KEYSTORE_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mqmonitor-secret
                  key: mqTlsKeystorePassword
            - name: MQ_TLS_TRUSTSTORE_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mqmonitor-secret
                  key: mqTlsTruststorePassword
          volumeMounts:
            - mountPath: /etc/certs
              readOnly: true
              name: volume-certs
      volumes:
        - name: volume-certs
          secret:
            secretName: mqmonitor-secret
            defaultMode: 0640
            items:
              - key: mqTlsKeystore
                path: keystore.jks
              - key: mqTlsTruststore
                path: truststore.jks